{
  "uid" : "e3a3524c6d1f3dee",
  "name" : "test_function",
  "fullName" : "test_assert1#test_function",
  "historyId" : "c07f55d59f64ccfc8125eb6a533de7cc",
  "time" : {
    "start" : 1597305143983,
    "stop" : 1597305143983,
    "duration" : 0
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: 判断 a 为偶数，当前 a 的值为：3\nassert (3 % 2) == 0",
  "statusTrace" : "def test_function():\n        # assert f() == 4\n        a = f()\n>       assert a % 2 == 0, \"判断 a 为偶数，当前 a 的值为：%s\" %a\nE       AssertionError: 判断 a 为偶数，当前 a 的值为：3\nE       assert (3 % 2) == 0\n\ntest_assert1.py:9: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "test_assert1"
  }, {
    "name" : "host",
    "value" : "PC-20160818TLFG"
  }, {
    "name" : "thread",
    "value" : "25396-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_assert1"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "e3a3524c6d1f3dee.json",
  "parameterValues" : [ ]
}